// Demo catalogue. All games, studios and trophies are fictional. Real data
// arrives through PSN sync once PSN_NPSSO is configured.

export type Archetype =
  | "soulslike" | "racing" | "horror" | "shooter" | "cozy" | "fighting" | "narrative"
  | "tactics" | "platformer" | "jrpg" | "sports" | "stealth" | "openworld" | "party";

export type TrophySpec = {
  name: string;
  description: string;
  type: "GOLD" | "SILVER" | "BRONZE";
  hidden?: boolean;
  missable?: boolean;
  online?: boolean;
  /** Relative difficulty 0 (everyone) to 1 (almost nobody). Drives earn rate. */
  hard?: number;
  collectible?: boolean;
  speedrun?: boolean;
};

export type GameSpec = {
  title: string;
  archetype: Archetype;
  genre: string;
  platforms: string;
  developer: string;
  publisher: string;
  release: string;
  difficulty: number;
  hours: number;
  playthroughs: number;
  online?: boolean;
  description: string;
  platinum: string;
  chapters: string[];
  collectibles: [noun: string, count: number, missable?: boolean][];
  hardMode?: string;
  speedrun?: [name: string, limit: string];
  extras?: TrophySpec[];
  dlc?: { name: string; release: string; trophies: TrophySpec[] }[];
};

export const ARCHETYPE_EXTRAS: Record<Archetype, TrophySpec[]> = {
  soulslike: [
    { name: "Perfect Guard", description: "Parry 100 attacks.", type: "BRONZE", hard: 0.3 },
    { name: "Untouchable", description: "Defeat any boss without taking damage.", type: "GOLD", hard: 0.8 },
    { name: "Forged Anew", description: "Upgrade a weapon to its maximum level.", type: "SILVER", hard: 0.45 },
    { name: "Ember Hoarder", description: "Hold 500,000 embers at once.", type: "BRONZE", hard: 0.35 },
    { name: "Humble Beginnings", description: "Defeat the first boss at base level.", type: "SILVER", hard: 0.7 },
  ],
  racing: [
    { name: "Photo Finish", description: "Win a race by less than 0.05 seconds.", type: "BRONZE", hard: 0.35 },
    { name: "Clean Sweep", description: "Win a championship without hitting a wall.", type: "SILVER", hard: 0.55 },
    { name: "Garage Queen", description: "Own 50 cars.", type: "SILVER", hard: 0.5 },
    { name: "Airtime", description: "Stay airborne for 5 seconds.", type: "BRONZE", hard: 0.15 },
    { name: "Gold Standard", description: "Earn gold in every license test.", type: "GOLD", hard: 0.75 },
  ],
  horror: [
    { name: "Nerves of Steel", description: "Complete a chapter without using a heal item.", type: "BRONZE", hard: 0.35 },
    { name: "Pacifist", description: "Finish the story without killing a stalker.", type: "GOLD", hard: 0.75, missable: true },
    { name: "Archivist", description: "Read every file in a single playthrough.", type: "SILVER", hard: 0.5, missable: true },
    { name: "Don't Look Back", description: "Escape the hospital in under 4 minutes.", type: "BRONZE", hard: 0.3 },
  ],
  shooter: [
    { name: "Headhunter", description: "Get 500 headshots.", type: "BRONZE", hard: 0.3 },
    { name: "Long Shot", description: "Get a kill from over 300 metres.", type: "BRONZE", hard: 0.25 },
    { name: "Arsenal", description: "Fully upgrade every weapon.", type: "GOLD", hard: 0.6 },
    { name: "Squad Goals", description: "Win 25 online matches.", type: "SILVER", hard: 0.6, online: true },
    { name: "MVP", description: "Finish top of the scoreboard in an online match.", type: "BRONZE", hard: 0.45, online: true },
  ],
  cozy: [
    { name: "Five Stars", description: "Earn a five-star review.", type: "BRONZE", hard: 0.1 },
    { name: "Master Chef", description: "Learn every recipe.", type: "GOLD", hard: 0.55 },
    { name: "Regulars", description: "Max out friendship with 10 villagers.", type: "SILVER", hard: 0.45 },
    { name: "Seasonal", description: "Play through all four seasons.", type: "BRONZE", hard: 0.25 },
  ],
  fighting: [
    { name: "Combo Scholar", description: "Complete every combo trial.", type: "GOLD", hard: 0.85 },
    { name: "Ranked Up", description: "Reach Diamond rank online.", type: "GOLD", hard: 0.8, online: true },
    { name: "First Blood", description: "Win a ranked match.", type: "BRONZE", hard: 0.25, online: true },
    { name: "Perfect!", description: "Win a round without taking damage.", type: "BRONZE", hard: 0.2 },
    { name: "Arcade Legend", description: "Clear arcade mode with every fighter.", type: "SILVER", hard: 0.55 },
  ],
  narrative: [
    { name: "All Paths", description: "See every ending.", type: "GOLD", hard: 0.45 },
    { name: "Kind Words", description: "Comfort Mara at the lighthouse.", type: "BRONZE", hard: 0.25, missable: true },
    { name: "Wanderer", description: "Explore every optional area.", type: "SILVER", hard: 0.4, missable: true },
  ],
  tactics: [
    { name: "No One Left Behind", description: "Finish a campaign act without losing a unit.", type: "GOLD", hard: 0.7 },
    { name: "Grand Strategist", description: "Win a battle in 3 turns or fewer.", type: "SILVER", hard: 0.45 },
    { name: "Promotion", description: "Promote a unit to a master class.", type: "BRONZE", hard: 0.2 },
    { name: "Bonds of Iron", description: "Reach max support with any pair.", type: "BRONZE", hard: 0.3, missable: true },
  ],
  platformer: [
    { name: "Deathless", description: "Clear a world without dying.", type: "GOLD", hard: 0.9 },
    { name: "Frame Perfect", description: "Clear the golden strawberry room.", type: "SILVER", hard: 0.75 },
    { name: "1000 Deaths", description: "Die 1,000 times. Keep going.", type: "BRONZE", hard: 0.2 },
    { name: "B-Sides", description: "Clear every B-side level.", type: "GOLD", hard: 0.85 },
  ],
  jrpg: [
    { name: "Bestiary", description: "Complete the monster encyclopedia.", type: "GOLD", hard: 0.65, missable: true },
    { name: "Overkill", description: "Deal 99,999 damage in one hit.", type: "SILVER", hard: 0.5 },
    { name: "Side Story", description: "Complete every side quest.", type: "GOLD", hard: 0.6, missable: true },
    { name: "Fisherman", description: "Catch every fish.", type: "SILVER", hard: 0.55 },
    { name: "Superboss", description: "Defeat the Weapon of the Deep.", type: "GOLD", hard: 0.8 },
  ],
  sports: [
    { name: "900", description: "Land a 900.", type: "SILVER", hard: 0.5 },
    { name: "Sick Line", description: "Score 1,000,000 points in a single combo.", type: "GOLD", hard: 0.75 },
    { name: "Local Legend", description: "Complete every challenge in a park.", type: "BRONZE", hard: 0.3 },
    { name: "Deck Builder", description: "Unlock every board.", type: "SILVER", hard: 0.45 },
  ],
  stealth: [
    { name: "Ghost", description: "Complete a mission undetected.", type: "SILVER", hard: 0.45 },
    { name: "Silent Assassin", description: "Finish the game without raising an alarm.", type: "GOLD", hard: 0.85 },
    { name: "Gadgeteer", description: "Use every gadget.", type: "BRONZE", hard: 0.2 },
    { name: "Clean Hands", description: "Complete a mission without knocking anyone out.", type: "BRONZE", hard: 0.4 },
  ],
  openworld: [
    { name: "Cartographer", description: "Reveal the entire map.", type: "SILVER", hard: 0.35 },
    { name: "Legend of the Road", description: "Complete every side quest.", type: "GOLD", hard: 0.55 },
    { name: "Tamer", description: "Tame every mount.", type: "BRONZE", hard: 0.3 },
    { name: "Master Crafter", description: "Craft a legendary item.", type: "SILVER", hard: 0.4 },
    { name: "Photo Mode", description: "Take a picture in photo mode.", type: "BRONZE", hard: 0.05 },
  ],
  party: [
    { name: "Party Starter", description: "Win a match with 4 players.", type: "BRONZE", hard: 0.2 },
    { name: "Champion", description: "Win 50 online matches.", type: "GOLD", hard: 0.8, online: true },
    { name: "Dressed Up", description: "Unlock 100 cosmetics.", type: "SILVER", hard: 0.55 },
    { name: "Friends Online", description: "Play an online match with a friend.", type: "BRONZE", hard: 0.3, online: true },
  ],
};

export const GAMES: GameSpec[] = [
  {
    title: "Ashen Crown",
    archetype: "soulslike",
    genre: "Action RPG",
    platforms: "PS5",
    developer: "Cinderforge Studio",
    publisher: "Nightfall Interactive",
    release: "2024-03-14",
    difficulty: 8,
    hours: 70,
    playthroughs: 3,
    description:
      "A punishing dark-fantasy action RPG set in a kingdom where the dead crown themselves. Precise parries, brutal bosses and three endings.",
    platinum: "Crown of Ash",
    chapters: ["The Pale Gate", "Harrowmere", "Sunken Chapel", "The Bone Orchard", "Ivory Spire", "Throne of Cinders"],
    collectibles: [["Relics of the Old King", 40, false], ["Ashen Hymns", 12, true]],
    hardMode: "Cinder's Oath",
    speedrun: ["Kindled Haste", "3 hours"],
    extras: [
      { name: "The Usurper", description: "Obtain the Usurper ending.", type: "GOLD", hidden: true, hard: 0.6 },
      { name: "The Faithful", description: "Obtain the Faithful ending.", type: "GOLD", hidden: true, hard: 0.55, missable: true },
    ],
    dlc: [
      {
        name: "Frostbound Vigil",
        release: "2024-11-05",
        trophies: [
          { name: "Into the Frost", description: "Enter the Vigil.", type: "BRONZE", hard: 0.1 },
          { name: "Warden of Winter", description: "Defeat the Frost Warden.", type: "GOLD", hard: 0.6 },
          { name: "Cold Relics", description: "Find all 10 Frost Relics.", type: "SILVER", hard: 0.5, collectible: true },
          { name: "Glacial Pace", description: "Defeat the Warden without dodging.", type: "SILVER", hard: 0.85 },
        ],
      },
    ],
  },
  {
    title: "Neon Rift: Overdrive",
    archetype: "racing",
    genre: "Arcade Racing",
    platforms: "PS5,PS4",
    developer: "Parallax Motors",
    publisher: "Voltline",
    release: "2023-06-22",
    difficulty: 4,
    hours: 25,
    playthroughs: 1,
    online: true,
    description: "Synthwave street racing through a city that rebuilds itself every night. Drift, boost and outrun the grid.",
    platinum: "Beyond the Grid",
    chapters: ["Rookie Circuit", "Downtown Nights", "Harbor Heat", "Skyline Sprint", "The Rift Cup"],
    collectibles: [["Neon Billboards", 60, false], ["Hidden Garages", 15, false]],
    hardMode: "Overclocked",
    speedrun: ["Lightspeed", "the Rift Cup under 12:00"],
    extras: [{ name: "Grid Warrior", description: "Win 10 online races.", type: "SILVER", hard: 0.55, online: true }],
  },
  {
    title: "Hollow Tide",
    archetype: "horror",
    genre: "Survival Horror",
    platforms: "PS5",
    developer: "Grey Harbor Games",
    publisher: "Nightfall Interactive",
    release: "2023-10-27",
    difficulty: 5,
    hours: 18,
    playthroughs: 2,
    description: "A fishing town drowned for thirty years resurfaces overnight. Scarce ammo, tight corridors, and something in the water.",
    platinum: "Low Tide",
    chapters: ["Arrival", "The Cannery", "St. Brine's Hospital", "The Lighthouse", "Beneath"],
    collectibles: [["Tide Journals", 30, true], ["Brass Keys", 8, false]],
    hardMode: "Drowned",
    speedrun: ["Riptide", "3 hours"],
  },
  {
    title: "Starfall Legion",
    archetype: "shooter",
    genre: "Sci-fi Shooter",
    platforms: "PS5,PS4",
    developer: "Orbit Nine",
    publisher: "Helix Entertainment",
    release: "2022-11-08",
    difficulty: 6,
    hours: 40,
    playthroughs: 1,
    online: true,
    description: "A squad shooter where your orbital fleet reshapes the battlefield. Campaign, co-op raids and competitive modes.",
    platinum: "Legion Eternal",
    chapters: ["Drop Zone", "Ember Moon", "The Siege of Karth", "Void Station", "Last Light"],
    collectibles: [["Intel Drives", 45, false]],
    hardMode: "Legendary",
    dlc: [
      {
        name: "Operation Blackstar",
        release: "2023-05-16",
        trophies: [
          { name: "Blackstar Rising", description: "Complete Operation Blackstar.", type: "SILVER", hard: 0.2 },
          { name: "Raid Leader", description: "Clear the Blackstar raid on Heroic.", type: "GOLD", hard: 0.8, online: true },
          { name: "No Casualties", description: "Finish Blackstar without a squadmate going down.", type: "SILVER", hard: 0.65 },
        ],
      },
    ],
  },
  {
    title: "Kitsune's Path",
    archetype: "openworld",
    genre: "Action Adventure",
    platforms: "PS5",
    developer: "Moonpetal",
    publisher: "Helix Entertainment",
    release: "2024-07-19",
    difficulty: 3,
    hours: 50,
    playthroughs: 1,
    description: "Follow a nine-tailed spirit across a painted feudal island. Swordplay, shrines, and a world that changes with the seasons.",
    platinum: "Nine Tails",
    chapters: ["Fox Shrine", "Village of Lanterns", "Bamboo Sea", "Mount Kagari", "The Spirit Court", "Dawn"],
    collectibles: [["Fox Shrines", 49, false], ["Haiku Stones", 20, false], ["Hot Springs", 12, false]],
  },
  {
    title: "Pixel Pantry",
    archetype: "cozy",
    genre: "Simulation",
    platforms: "PS5,PS4",
    developer: "Little Oven",
    publisher: "Little Oven",
    release: "2023-02-09",
    difficulty: 2,
    hours: 22,
    playthroughs: 1,
    description: "Run a tiny pixel-art café in a seaside town. Cook, decorate, and befriend the regulars.",
    platinum: "Chef's Kiss",
    chapters: ["Grand Opening", "Spring Menu", "Summer Festival", "Harvest Moon", "Winter Feast"],
    collectibles: [["Secret Recipes", 25, false]],
  },
  {
    title: "Iron Verdict",
    archetype: "fighting",
    genre: "Fighting",
    platforms: "PS5,PS4",
    developer: "Ringside Labs",
    publisher: "Voltline",
    release: "2023-09-01",
    difficulty: 7,
    hours: 60,
    playthroughs: 1,
    online: true,
    description: "A 2D fighter built around a verdict meter: land reads, earn the crowd, and seal the round with a Final Judgement.",
    platinum: "Case Closed",
    chapters: ["Opening Statements", "Cross Examination", "Closing Arguments"],
    collectibles: [["Character Stories", 20, false]],
  },
  {
    title: "The Last Lantern",
    archetype: "narrative",
    genre: "Adventure",
    platforms: "PS5,PS4",
    developer: "Quiet Hours",
    publisher: "Quiet Hours",
    release: "2024-01-30",
    difficulty: 1,
    hours: 8,
    playthroughs: 2,
    description: "A short, tender story about a lighthouse keeper's last winter. Choices matter, and some moments only happen once.",
    platinum: "Keeper of the Light",
    chapters: ["First Frost", "The Letter", "Storm Night", "Thaw"],
    collectibles: [["Postcards", 16, true]],
  },
  {
    title: "Cinder Knights Tactics",
    archetype: "tactics",
    genre: "Strategy RPG",
    platforms: "PS5",
    developer: "Cinderforge Studio",
    publisher: "Nightfall Interactive",
    release: "2025-02-20",
    difficulty: 5,
    hours: 75,
    playthroughs: 2,
    description: "Grid-based tactics in the Ashen Crown universe. Permadeath optional, regret guaranteed.",
    platinum: "Order of Cinders",
    chapters: ["Act I: Oathbreakers", "Act II: The Long March", "Act III: Siegeborn", "Act IV: Ashfall"],
    collectibles: [["Battle Standards", 24, true]],
    hardMode: "Ironclad",
  },
  {
    title: "Glacier Run",
    archetype: "platformer",
    genre: "Platformer",
    platforms: "PS5,PS4",
    developer: "Two Penguins",
    publisher: "Two Penguins",
    release: "2022-05-12",
    difficulty: 9,
    hours: 35,
    playthroughs: 1,
    description: "A razor-precise platformer about climbing a mountain that doesn't want to be climbed.",
    platinum: "Summit",
    chapters: ["Basecamp", "Ice Caves", "The Crevasse", "Whiteout", "The Peak"],
    collectibles: [["Golden Feathers", 120, false]],
    speedrun: ["Avalanche", "the full climb under 45:00"],
  },
  {
    title: "Deep Signal",
    archetype: "horror",
    genre: "Sci-fi Horror",
    platforms: "PS5",
    developer: "Grey Harbor Games",
    publisher: "Helix Entertainment",
    release: "2025-04-10",
    difficulty: 4,
    hours: 14,
    playthroughs: 1,
    description: "A deep-sea research station stopped transmitting. You're the repair tech they sent down anyway.",
    platinum: "Signal Restored",
    chapters: ["Descent", "Hydroponics", "The Trench Lab", "Signal Source"],
    collectibles: [["Audio Logs", 36, false]],
  },
  {
    title: "Mythbound Chronicles",
    archetype: "jrpg",
    genre: "JRPG",
    platforms: "PS5,PS4",
    developer: "Aozora Works",
    publisher: "Aozora Works",
    release: "2023-12-07",
    difficulty: 4,
    hours: 95,
    playthroughs: 1,
    description: "A sprawling turn-based JRPG with a party of seven, a floating continent, and far too many side quests.",
    platinum: "Chronicler",
    chapters: ["Prologue: Skyfall", "Chapter 1: Windmere", "Chapter 2: The Salt Desert", "Chapter 3: Aetheria", "Chapter 4: The Undercity", "Finale: Myth's End"],
    collectibles: [["Star Fragments", 77, true], ["Treasure Maps", 20, false]],
  },
  {
    title: "Street Kings 99",
    archetype: "sports",
    genre: "Skateboarding",
    platforms: "PS4",
    developer: "Grindline",
    publisher: "Voltline",
    release: "2021-08-19",
    difficulty: 5,
    hours: 20,
    playthroughs: 1,
    description: "Late-90s skate energy with a modern trick system. Ten parks, a tape-hunt, and a punk soundtrack.",
    platinum: "King of the Streets",
    chapters: ["Warehouse", "School Yard", "Downtown", "The Docks", "Mega Ramp"],
    collectibles: [["Secret Tapes", 10, false], ["S-K-A-T-E Letters", 50, false]],
  },
  {
    title: "Orbital Farm",
    archetype: "cozy",
    genre: "Simulation",
    platforms: "PS5",
    developer: "Little Oven",
    publisher: "Helix Entertainment",
    release: "2025-06-03",
    difficulty: 2,
    hours: 40,
    playthroughs: 1,
    description: "Grow crops in zero gravity aboard a derelict space station. Automate, decorate, and feed the crew.",
    platinum: "Harvest Moon(s)",
    chapters: ["Hydro Bay", "The Greenhouse Ring", "Solar Array", "Station Restored"],
    collectibles: [["Seed Pods", 40, false]],
  },
  {
    title: "Shadow Protocol",
    archetype: "stealth",
    genre: "Stealth Action",
    platforms: "PS5",
    developer: "Blackglass",
    publisher: "Nightfall Interactive",
    release: "2024-09-26",
    difficulty: 6,
    hours: 28,
    playthroughs: 2,
    description: "A systemic stealth thriller. Every mission has a dozen ways in, and the rating screen remembers all of them.",
    platinum: "Protocol Complete",
    chapters: ["Infiltration", "The Gala", "Blacksite", "Crosswire", "Endgame"],
    collectibles: [["Dossiers", 32, true]],
    hardMode: "Professional",
    speedrun: ["Clockwork", "each mission under its par time"],
  },
  {
    title: "Rally Legends",
    archetype: "racing",
    genre: "Sim Racing",
    platforms: "PS5",
    developer: "Parallax Motors",
    publisher: "Voltline",
    release: "2025-01-16",
    difficulty: 6,
    hours: 55,
    playthroughs: 1,
    online: true,
    description: "Gravel, snow and tarmac across 12 countries. Brutal handling model, beautiful damage.",
    platinum: "Legend Status",
    chapters: ["Junior Rally", "Continental Cup", "World Rally", "Legends Series"],
    collectibles: [["Liveries", 30, false]],
    hardMode: "Hardcore Damage",
  },
  {
    title: "Bramble & Bone",
    archetype: "platformer",
    genre: "Metroidvania",
    platforms: "PS5,PS4",
    developer: "Thornlight",
    publisher: "Thornlight",
    release: "2023-04-18",
    difficulty: 6,
    hours: 26,
    playthroughs: 1,
    description: "A hand-drawn metroidvania about a skeleton knight in an overgrown underworld.",
    platinum: "Rootbound",
    chapters: ["The Hollow", "Mossy Crypts", "The Thorn Palace", "Heartwood"],
    collectibles: [["Bone Shards", 60, false], ["Charms", 30, false]],
    speedrun: ["Bare Bones", "2 hours"],
  },
  {
    title: "Tiny Titans Arena",
    archetype: "party",
    genre: "Party Brawler",
    platforms: "PS5,PS4",
    developer: "Bouncy Castle",
    publisher: "Helix Entertainment",
    release: "2024-05-09",
    difficulty: 3,
    hours: 15,
    playthroughs: 1,
    online: true,
    description: "Chaotic four-player brawls with toy soldiers. Local and online.",
    platinum: "Tiny but Mighty",
    chapters: ["Toy Box", "Kitchen Chaos", "Backyard Brawl"],
    collectibles: [["Stickers", 80, false]],
  },
  {
    title: "Echoes of Aurora",
    archetype: "openworld",
    genre: "Open World RPG",
    platforms: "PS5",
    developer: "Northlight Forge",
    publisher: "Aurora Games",
    release: "2025-08-28",
    difficulty: 3,
    hours: 110,
    playthroughs: 1,
    description: "A northern open world where the aurora rewrites history. Build a clan, raid ruins, and chase echoes of the past.",
    platinum: "Aurora Borne",
    chapters: ["The Longhouse", "Frostmarch", "Skarfell", "The Sky Road", "Aurora's Heart", "Epilogue"],
    collectibles: [["Rune Stones", 88, false], ["Echo Shards", 30, false]],
    dlc: [
      {
        name: "Shores of Embers",
        release: "2026-03-12",
        trophies: [
          { name: "Landfall", description: "Arrive on the Ember Shores.", type: "BRONZE", hard: 0.1 },
          { name: "Firewalker", description: "Complete the Shores of Embers story.", type: "GOLD", hard: 0.35 },
          { name: "Obsidian Hoard", description: "Collect every Obsidian Idol.", type: "SILVER", hard: 0.55, collectible: true },
        ],
      },
      {
        name: "The Drowned Kings",
        release: "2026-08-20",
        trophies: [
          { name: "Below the Ice", description: "Enter the Drowned Halls.", type: "BRONZE", hard: 0.15 },
          { name: "Kingslayer", description: "Defeat all three Drowned Kings.", type: "GOLD", hard: 0.6 },
          { name: "Cold Blooded", description: "Defeat a Drowned King without healing.", type: "SILVER", hard: 0.75 },
        ],
      },
    ],
  },
  {
    title: "Quickdraw Quest",
    archetype: "party",
    genre: "Arcade",
    platforms: "PS5,PS4",
    developer: "Snack Size Games",
    publisher: "Snack Size Games",
    release: "2024-10-10",
    difficulty: 1,
    hours: 2,
    playthroughs: 1,
    description: "A bite-sized western shooting gallery. Short, sweet, and famously generous with trophies.",
    platinum: "Fastest Gun",
    chapters: ["Dusty Gulch", "Tumbleweed Pass", "High Noon"],
    collectibles: [["Sheriff Badges", 9, false]],
  },
];

export const USERS: { username: string; onlineId: string; country: string; bio?: string; visibility?: string }[] = [
  { username: "platinumpanda", onlineId: "PlatinumPanda", country: "GB", bio: "600+ plats. Ultra rares or bust." },
  { username: "rareaura", onlineId: "Rare_Aura", country: "US", bio: "Hunting the rarest trophies on PSN." },
  { username: "kitsunekai", onlineId: "KitsuneKai", country: "JP", bio: "JRPGs forever." },
  { username: "ghostbyte", onlineId: "GhostByte_", country: "DE" },
  { username: "lunarlotus", onlineId: "LunarLotus", country: "FR", bio: "Cozy games + soulslikes. Balance." },
  { username: "trophytitan", onlineId: "TrophyTitan99", country: "US", bio: "Completionist. 100% or it didn't happen." },
  { username: "silverfang", onlineId: "SilverFang", country: "CA" },
  { username: "bronzebaron", onlineId: "Bronze_Baron", country: "AU", bio: "I love a good bronze." },
  { username: "nightowl", onlineId: "NightOwlGG", country: "BR" },
  { username: "pixelpilgrim", onlineId: "PixelPilgrim", country: "ES", bio: "Indies & platformers." },
  { username: "stormcaller", onlineId: "Storm-Caller", country: "SE" },
  { username: "dustdevil", onlineId: "DustDevil", country: "MX" },
  { username: "emberknight", onlineId: "EmberKnight", country: "IT", bio: "Ashen Crown veteran." },
  { username: "froststep", onlineId: "FrostStep", country: "NO" },
  { username: "questcraft", onlineId: "QuestCraft", country: "PL" },
  { username: "novablade", onlineId: "NovaBlade", country: "KR" },
  { username: "tidehunter", onlineId: "TideHunter", country: "NL" },
  { username: "cobaltcrow", onlineId: "CobaltCrow", country: "US" },
  { username: "mapleleaf", onlineId: "MapleLeaf_", country: "CA" },
  { username: "sakuradrift", onlineId: "SakuraDrift", country: "JP" },
  { username: "ironoath", onlineId: "IronOath", country: "GB", visibility: "FRIENDS" },
  { username: "voidwalker", onlineId: "VoidWalker", country: "DE" },
  { username: "solarflare", onlineId: "SolarFlare", country: "AU" },
  { username: "quietstorm", onlineId: "QuietStorm", country: "IE" },
  { username: "retroranger", onlineId: "RetroRanger", country: "US", bio: "PS1 kid, PS5 adult." },
  { username: "lanternlight", onlineId: "LanternLight", country: "PT" },
  { username: "hexhunter", onlineId: "HexHunter", country: "FI" },
  { username: "moonrider", onlineId: "MoonRider", country: "AR" },
  { username: "shadowfox", onlineId: "Shadow_Fox", country: "GB" },
  { username: "crimsonace", onlineId: "CrimsonAce", country: "PL" },
  { username: "glitchgoblin", onlineId: "GlitchGoblin", country: "US", visibility: "PRIVATE" },
  { username: "starlitsage", onlineId: "StarlitSage", country: "FR" },
  { username: "boostbuddy", onlineId: "BoostBuddy", country: "LT", bio: "Always up for a boosting session." },
  { username: "casualcarl", onlineId: "CasualCarl", country: "GB", bio: "Just here for fun." },
  { username: "speedyspectre", onlineId: "SpeedySpectre", country: "US", bio: "Speedruns & speed plats." },
];
